baseURL = 'https://www.sfu.ca/~mulhaq/'
languageCode = 'en-us'
title = 'Mateen Ulhaq'
theme = 'hugo-astatine-theme'
# theme = 'gohugo-theme-ananke'
# theme = 'hugo-theme-notrack'
# theme = 'poison'
# theme = 'theme-academic-cv'

preserveTaxonomyNames = true
rssLimit = 10
paginate = 10

# Code highlighting
pygmentsCodefences = true
pygmentsStyle = "native"


# Taxonomies (only tags and categories are supported out of the box but you can add more)
[taxonomies]
    category = "categories"
    tag = "tags"


# Configure permalinks style
[permalinks]
    # post = "post/:slug/"
    page = "/:slug/"


# Configure main navbar links. They can have a weight to select the order.
# This links to content within the content/post/ folder
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = -150

# content/about/index.md
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = -110

# content/about/index.md
[[menu.main]]
    name = "Art"
    url = "/art/"
    weight = -115

# Make the tags and categories pages accessible directly from the navbar.
# [[menu.main]]
#     name = "Tags"
#     url = "/tags/"
#     weight = -120

# [[menu.main]]
#     name = "Categories"
#     url = "/categories/"
#     weight = -130


[params]
    # Site description. Individual pages can have descriptions too but if
    # missing it will fallback to that one.
    description = """Mateen Ulhaq's personal website."""

    authorName = "Mateen Ulhaq"

    # Main image for the author. This will be the default image for SEO.
    [params.imgname]
        name = "assets/img/expanse.jpg"
        # alt = "Profile picture"

    # Indicate if you host KaTeX yourself. Defaults to using the CDN KaTeX.
    # hostedKaTex = false

    # Optional: add a twitter handle and mastodon handle for SEO.
    # [params.twitter]
        # name = "@username"
    # [params.mastodon]
        # name = "@username"
        # host = "mastodon.social"

    # Enable link to feed in footer
    blogrss = true

    # Enable pingback and webmention via webmention.io
    # webmention = "example.com"


[sitemap]
  filename = "sitemap.xml"


[markup.goldmark.renderer]
unsafe = true  # Allow raw HTML

